# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QCheckBox, QComboBox,
    QDoubleSpinBox, QGroupBox, QLabel, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(966, 1122)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.buttonSave = QPushButton(self.centralwidget)
        self.buttonSave.setObjectName(u"buttonSave")
        self.buttonSave.setGeometry(QRect(510, 710, 150, 26))
        self.buttonSave.setStyleSheet(u"background-color: #27ae60; color: white; font-weight: bold; border-radius: 4px;")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.buttonSave.setIcon(icon)
        self.buttonCopy = QPushButton(self.centralwidget)
        self.buttonCopy.setObjectName(u"buttonCopy")
        self.buttonCopy.setGeometry(QRect(680, 710, 150, 26))
        self.buttonCopy.setAutoFillBackground(False)
        self.buttonCopy.setStyleSheet(u"background-color: #3498db; color: white; font-weight: bold; border-radius: 4px;")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.buttonCopy.setIcon(icon1)
        self.buttonCopy.setAutoDefault(False)
        self.buttonCopy.setFlat(False)
        self.buttonClose = QPushButton(self.centralwidget)
        self.buttonClose.setObjectName(u"buttonClose")
        self.buttonClose.setGeometry(QRect(430, 790, 80, 26))
        self.buttonClose.setStyleSheet(u"background-color: #27ae60; color: white; font-weight: bold; border-radius: 4px;")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.WindowClose))
        self.buttonClose.setIcon(icon2)
        self.groupBoxInput = QGroupBox(self.centralwidget)
        self.groupBoxInput.setObjectName(u"groupBoxInput")
        self.groupBoxInput.setGeometry(QRect(310, 300, 481, 131))
        self.plainTextEdit = QPlainTextEdit(self.groupBoxInput)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(20, 30, 391, 81))
        self.groupBoxPreview = QGroupBox(self.centralwidget)
        self.groupBoxPreview.setObjectName(u"groupBoxPreview")
        self.groupBoxPreview.setGeometry(QRect(70, 40, 700, 251))
        self.labelFontDir = QLabel(self.centralwidget)
        self.labelFontDir.setObjectName(u"labelFontDir")
        self.labelFontDir.setGeometry(QRect(70, 700, 401, 51))
        self.labelFont = QLabel(self.centralwidget)
        self.labelFont.setObjectName(u"labelFont")
        self.labelFont.setGeometry(QRect(550, 590, 66, 18))
        self.comboFont = QComboBox(self.centralwidget)
        self.comboFont.setObjectName(u"comboFont")
        self.comboFont.setGeometry(QRect(550, 630, 221, 26))
        self.buttonIcon = QPushButton(self.centralwidget)
        self.buttonIcon.setObjectName(u"buttonIcon")
        self.buttonIcon.setGeometry(QRect(660, 580, 94, 26))
        self.groupBoxFootprint = QGroupBox(self.centralwidget)
        self.groupBoxFootprint.setObjectName(u"groupBoxFootprint")
        self.groupBoxFootprint.setGeometry(QRect(540, 460, 218, 103))
        self.labelLayer = QLabel(self.groupBoxFootprint)
        self.labelLayer.setObjectName(u"labelLayer")
        self.labelLayer.setGeometry(QRect(12, 33, 41, 18))
        self.comboLayer = QComboBox(self.groupBoxFootprint)
        self.comboLayer.setObjectName(u"comboLayer")
        self.comboLayer.setGeometry(QRect(112, 33, 86, 26))
        self.labelAnchor = QLabel(self.groupBoxFootprint)
        self.labelAnchor.setObjectName(u"labelAnchor")
        self.labelAnchor.setGeometry(QRect(12, 65, 52, 18))
        self.comboAnchor = QComboBox(self.groupBoxFootprint)
        self.comboAnchor.setObjectName(u"comboAnchor")
        self.comboAnchor.setGeometry(QRect(112, 65, 86, 26))
        self.groupBoxPadding = QGroupBox(self.centralwidget)
        self.groupBoxPadding.setObjectName(u"groupBoxPadding")
        self.groupBoxPadding.setGeometry(QRect(300, 440, 218, 251))
        self.labelTop = QLabel(self.groupBoxPadding)
        self.labelTop.setObjectName(u"labelTop")
        self.labelTop.setGeometry(QRect(12, 54, 29, 18))
        self.doubleSpinTop = QDoubleSpinBox(self.groupBoxPadding)
        self.doubleSpinTop.setObjectName(u"doubleSpinTop")
        self.doubleSpinTop.setGeometry(QRect(112, 54, 65, 27))
        self.doubleSpinTop.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinTop.setDecimals(1)
        self.doubleSpinTop.setSingleStep(0.100000000000000)
        self.doubleSpinTop.setValue(1.000000000000000)
        self.labelBottom = QLabel(self.groupBoxPadding)
        self.labelBottom.setObjectName(u"labelBottom")
        self.labelBottom.setGeometry(QRect(12, 108, 56, 18))
        self.doubleSpinBottom = QDoubleSpinBox(self.groupBoxPadding)
        self.doubleSpinBottom.setObjectName(u"doubleSpinBottom")
        self.doubleSpinBottom.setGeometry(QRect(112, 108, 65, 27))
        self.doubleSpinBottom.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinBottom.setDecimals(1)
        self.doubleSpinBottom.setSingleStep(0.100000000000000)
        self.doubleSpinBottom.setValue(1.000000000000000)
        self.labelLeft = QLabel(self.groupBoxPadding)
        self.labelLeft.setObjectName(u"labelLeft")
        self.labelLeft.setGeometry(QRect(12, 162, 32, 18))
        self.doubleSpinLeft = QDoubleSpinBox(self.groupBoxPadding)
        self.doubleSpinLeft.setObjectName(u"doubleSpinLeft")
        self.doubleSpinLeft.setGeometry(QRect(112, 162, 65, 27))
        self.doubleSpinLeft.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinLeft.setDecimals(1)
        self.doubleSpinLeft.setSingleStep(0.100000000000000)
        self.doubleSpinLeft.setValue(1.000000000000000)
        self.labelRight = QLabel(self.groupBoxPadding)
        self.labelRight.setObjectName(u"labelRight")
        self.labelRight.setGeometry(QRect(12, 216, 40, 18))
        self.doubleSpinRight = QDoubleSpinBox(self.groupBoxPadding)
        self.doubleSpinRight.setObjectName(u"doubleSpinRight")
        self.doubleSpinRight.setGeometry(QRect(112, 216, 65, 27))
        self.doubleSpinRight.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinRight.setDecimals(1)
        self.doubleSpinRight.setSingleStep(0.100000000000000)
        self.doubleSpinRight.setValue(1.000000000000000)
        self.groupBoxEdges = QGroupBox(self.centralwidget)
        self.groupBoxEdges.setObjectName(u"groupBoxEdges")
        self.groupBoxEdges.setGeometry(QRect(70, 300, 216, 121))
        self.labelLeftEdge = QLabel(self.groupBoxEdges)
        self.labelLeftEdge.setObjectName(u"labelLeftEdge")
        self.labelLeftEdge.setGeometry(QRect(10, 40, 69, 18))
        self.comboLeftEdge = QComboBox(self.groupBoxEdges)
        self.comboLeftEdge.setObjectName(u"comboLeftEdge")
        self.comboLeftEdge.setGeometry(QRect(120, 30, 86, 26))
        self.labelRightEdge = QLabel(self.groupBoxEdges)
        self.labelRightEdge.setObjectName(u"labelRightEdge")
        self.labelRightEdge.setGeometry(QRect(10, 70, 78, 18))
        self.comboRightEdge = QComboBox(self.groupBoxEdges)
        self.comboRightEdge.setObjectName(u"comboRightEdge")
        self.comboRightEdge.setGeometry(QRect(120, 70, 86, 26))
        self.groupBoxGeometry = QGroupBox(self.centralwidget)
        self.groupBoxGeometry.setObjectName(u"groupBoxGeometry")
        self.groupBoxGeometry.setGeometry(QRect(70, 430, 211, 261))
        self.labelAlignment = QLabel(self.groupBoxGeometry)
        self.labelAlignment.setObjectName(u"labelAlignment")
        self.labelAlignment.setGeometry(QRect(13, 34, 74, 18))
        self.comboAlignment = QComboBox(self.groupBoxGeometry)
        self.comboAlignment.setObjectName(u"comboAlignment")
        self.comboAlignment.setGeometry(QRect(117, 34, 86, 26))
        self.checkNoFrame = QCheckBox(self.groupBoxGeometry)
        self.checkNoFrame.setObjectName(u"checkNoFrame")
        self.checkNoFrame.setGeometry(QRect(13, 227, 174, 23))
        self.checkNoFrame.setStyleSheet(u"font-weight: bold; color: #e74c3c;")
        self.doubleSpinCorner = QDoubleSpinBox(self.groupBoxGeometry)
        self.doubleSpinCorner.setObjectName(u"doubleSpinCorner")
        self.doubleSpinCorner.setGeometry(QRect(117, 165, 65, 27))
        self.doubleSpinCorner.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinCorner.setDecimals(1)
        self.doubleSpinCorner.setSingleStep(0.100000000000000)
        self.checkNegative = QCheckBox(self.groupBoxGeometry)
        self.checkNegative.setObjectName(u"checkNegative")
        self.checkNegative.setGeometry(QRect(13, 198, 154, 23))
        self.labelBorder = QLabel(self.groupBoxGeometry)
        self.labelBorder.setObjectName(u"labelBorder")
        self.labelBorder.setGeometry(QRect(13, 132, 95, 18))
        self.doubleSpinBorder = QDoubleSpinBox(self.groupBoxGeometry)
        self.doubleSpinBorder.setObjectName(u"doubleSpinBorder")
        self.doubleSpinBorder.setGeometry(QRect(117, 132, 65, 27))
        self.doubleSpinBorder.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinBorder.setDecimals(1)
        self.doubleSpinBorder.setSingleStep(0.100000000000000)
        self.doubleSpinBorder.setValue(0.500000000000000)
        self.doubleSpinHeight = QDoubleSpinBox(self.groupBoxGeometry)
        self.doubleSpinHeight.setObjectName(u"doubleSpinHeight")
        self.doubleSpinHeight.setGeometry(QRect(117, 66, 65, 27))
        self.doubleSpinHeight.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinHeight.setDecimals(1)
        self.doubleSpinHeight.setSingleStep(0.100000000000000)
        self.doubleSpinHeight.setValue(5.000000000000000)
        self.doubleSpinSpacing = QDoubleSpinBox(self.groupBoxGeometry)
        self.doubleSpinSpacing.setObjectName(u"doubleSpinSpacing")
        self.doubleSpinSpacing.setGeometry(QRect(117, 99, 65, 27))
        self.doubleSpinSpacing.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.doubleSpinSpacing.setDecimals(1)
        self.doubleSpinSpacing.setSingleStep(0.100000000000000)
        self.labelSpacing = QLabel(self.groupBoxGeometry)
        self.labelSpacing.setObjectName(u"labelSpacing")
        self.labelSpacing.setGeometry(QRect(13, 99, 88, 18))
        self.labelHeight = QLabel(self.groupBoxGeometry)
        self.labelHeight.setObjectName(u"labelHeight")
        self.labelHeight.setGeometry(QRect(13, 66, 88, 18))
        self.labelCorner = QLabel(self.groupBoxGeometry)
        self.labelCorner.setObjectName(u"labelCorner")
        self.labelCorner.setGeometry(QRect(13, 165, 98, 18))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 966, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.buttonCopy.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Text Label Generator", None))
        self.buttonSave.setText(QCoreApplication.translate("MainWindow", u"Save .kicad_mod", None))
        self.buttonCopy.setText(QCoreApplication.translate("MainWindow", u"Copy to Clipboard", None))
        self.buttonClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.groupBoxInput.setTitle(QCoreApplication.translate("MainWindow", u"Text Input", None))
        self.groupBoxPreview.setTitle(QCoreApplication.translate("MainWindow", u"Preview", None))
        self.labelFontDir.setText(QCoreApplication.translate("MainWindow", u"Font Path:", None))
        self.labelFont.setText(QCoreApplication.translate("MainWindow", u"Fonts", None))
        self.buttonIcon.setText(QCoreApplication.translate("MainWindow", u"Pick Icon", None))
        self.groupBoxFootprint.setTitle(QCoreApplication.translate("MainWindow", u"Footprint Setup", None))
        self.labelLayer.setText(QCoreApplication.translate("MainWindow", u"Layer:", None))
        self.labelAnchor.setText(QCoreApplication.translate("MainWindow", u"Anchor:", None))
        self.groupBoxPadding.setTitle(QCoreApplication.translate("MainWindow", u"Padding", None))
        self.labelTop.setText(QCoreApplication.translate("MainWindow", u"Top:", None))
        self.labelBottom.setText(QCoreApplication.translate("MainWindow", u"Bottom:", None))
        self.labelLeft.setText(QCoreApplication.translate("MainWindow", u"Left:", None))
        self.labelRight.setText(QCoreApplication.translate("MainWindow", u"Right:", None))
        self.groupBoxEdges.setTitle(QCoreApplication.translate("MainWindow", u"Edges", None))
        self.labelLeftEdge.setText(QCoreApplication.translate("MainWindow", u"Left Edge:", None))
        self.labelRightEdge.setText(QCoreApplication.translate("MainWindow", u"Right Edge:", None))
        self.groupBoxGeometry.setTitle(QCoreApplication.translate("MainWindow", u"Geometry & Style", None))
        self.labelAlignment.setText(QCoreApplication.translate("MainWindow", u"Alignment:", None))
        self.checkNoFrame.setText(QCoreApplication.translate("MainWindow", u"No Frame (Text Only)", None))
        self.checkNegative.setText(QCoreApplication.translate("MainWindow", u"Negative (Inverted)", None))
        self.labelBorder.setText(QCoreApplication.translate("MainWindow", u"Border Width:", None))
        self.labelSpacing.setText(QCoreApplication.translate("MainWindow", u"Line Spacing:", None))
        self.labelHeight.setText(QCoreApplication.translate("MainWindow", u"Height (mm):", None))
        self.labelCorner.setText(QCoreApplication.translate("MainWindow", u"Corner Radius:", None))
    # retranslateUi

